export enum StackEnum {
  JS = "JavaScript",
  TS = "TypeScript",
  Angular = "Angular",
  Node = "Node.js",
  GraphQL = "GraphQL",
  MongoDB = "MongoDB",
  Vue = "Vue.js",
  Pinia = "Pinia",
  Express = "Express.js",
  Axios = "Axios",
  Docker = "Docker",
  Electron = "Electron",
  Nuxt = "Nuxt.js",
  Postgre = "PostgreSQL",
  SASS = "SASS/SCSS",
  Tailwind = "TailwindCSS",
  Tanstack = "TanStack",
  Vitest = "Vitest",
  Python = "Python",
  ChartJS = "Chart.js",
  Shadcn = "shadcn/ui",
  Supabase = "Supabase",
}